sudo: false
language: rust
os:
- linux
- osx
dist: trusty
osx_image: xcode8.1
rust: stable
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
  - RBLANK_RUBY_VERSION: 2.3.3
  - RBLANK_RUBY_VERSION: 2.4.0
matrix:
  include:
  - os: osx
    osx_image: xcode8
    env: RBLANK_RUBY_VERSION=2.3.3
  - os: osx
    osx_image: xcode8
    env: RBLANK_RUBY_VERSION=2.4.0

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle
  - $HOME/.cache/pip

before_install:
- |
  rvm install "$RBLANK_RUBY_VERSION"
  rvm use "$RBLANK_RUBY_VERSION"
  ruby --version
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which bundle > /dev/null; then
    gem install bundler
  fi
- bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

before_script:
- |
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which pip > /dev/null; then
    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py --user
  fi
  pip install 'travis-cargo<0.2' --user

script:
- travis-cargo build
- bundle exec rake test
- bundle exec rake thermite:tarball
- bundle exec rake install
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_blank
    CARGO=fake bundle exec rake install
  fi
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_blank
    gem install minitest
    CARGO=fake gem install pkg/*.gem
    ruby test/test_rusty_blank.rb
  fi
- if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi
